In [3]:
import pandas 

In [4]:
base_df = pandas.read_csv(r"C:\Users\pinto\Downloads\new stuff\TechCrunchcontinentalUSA.csv")

In [5]:
base_df.shape

(1460, 10)

In [6]:
base_df.describe()

numEmps     raisedAmt
count    567.000000  1.460000e+03
mean      95.721340  1.013149e+07
std      867.524287  1.866146e+07
min        0.000000  6.000000e+03
25%        8.000000  2.000000e+06
50%       20.000000  5.500000e+06
75%       50.000000  1.102500e+07
max    20000.000000  3.000000e+08

In [9]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

base_df.iloc[:,0] = labelencoder.fit_transform(base_df.iloc[:,0])
print(base_df.head(6)[["permalink","company"]])

   permalink       company
0        419      LifeLock
1        419      LifeLock
2        419      LifeLock
3        503   MyCityFaces
4        254      Flypaper
5        355  Infusionsoft


In [20]:
def own_transform(l):
    transform = sorted(set(l))
    return [transform.index(i) for i in l]

lot = ["call","all","call","ball","cat"]
print(labelencoder.fit_transform(lot))
print(own_transform(lot))

[2 0 2 1 3]
[2, 0, 2, 1, 3]


In [45]:
from numpy import array,argmax
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#define example
data =[ 'cold','cold','warm','cold','hot','hot','warm','cold','warm','hot']
values = array(data)
print(values)
#integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
#binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded),1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
#invert first example, (you can change 4,inverted & inverted2 is same)
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[4, :])])
inverted2 = label_encoder.inverse_transform(integer_encoded[4])
print(inverted,inverted2)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['hot'] ['hot']


D:\conda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
